### PR TITLE
Resolve deprecation warnings emitted by GitHub Actions

### PR DESCRIPTION
**Pull request by zml2008**
## What this PR does / Why we need it
These changes resolve deprecation warnings presented by GitHub Actions runs due to use of Node 12, plus warnings due to using deprecated set-state and set-output commands.

I've bumped the Node version to Node 16, plus bumped the TypeScript and associated build dependency versions to allow targeting ES2021, the newest JS version supported by Node 16. I've also updated the version of @actions/core to resolve the other deprecation warnings.

## Which issue(s) this PR fixes
These are the GitHub blog posts describing the deprecations:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

I'm personally not super familiar with JS development, so please don't be afraid to point out things I've done wrong here :)

### CODE REVIEW

**Comment by rupert-he** [comment]
Any news on when this might be merged and a new version of the action releases to GitHub marketplace?

**Comment by zml2008** [comment]
fwiw I've spun up a fork over at https://github.com/KyoriPowered/action-regex-match/ for the projects I use since there hasn't been any movement over here -- don't expect anything exciting but as long as we continue using this action I'll keep that working. That'd be a `uses: KyoriPowered/action-regex-match@v3` in workflows.

**Comment by smkjason** [comment]
I'd love to see this merged soon. Thanks!

**Review by aximov — APPROVED** [review]
I'm very sorry for the late review. As this update involves updating multiple elements simultaneously, I don't have strong confidence, but at least it seems to be working fine for the forked version, so I will merge it. Thank you very much for maintaining the fork. 🤗

**Comment by zliang-akamai** [comment]
@aximov can we do a release soon?

**Comment by edreinsM1** [comment]
When will this be released?

**Pull request merged**
